### ISSUE TITLE
Feature Request - Allow us to choose default model

### ISSUE THREAD

**Issue by Vigilence** [jiayev/GPT4V-Image-Captioner#12]
Hello!

I would like the ability to choose the default model that would be used for each session.  ATM I have to manually switch to the cog model I need instead of the default GPT which wastes time.

**Comment by SleeeepyZhou** [comment]
Thank you for the feedback! I've taken note of this issue, and I plan to add a button for choose after addressing the currently known bugs. Stay tuned for updates.

**Comment by Vigilence** [comment]
Thank you so much!

**Comment by SleeeepyZhou** [comment]
> Hello!
> 
> I would like the ability to choose the default model that would be used for each session. ATM I have to manually switch to the cog model I need instead of the default GPT which wastes time.

It has been updated now, you can try updating the file. It is recommended to run the installation script again before starting.

**Comment by Vigilence** [comment]
Thank you!
