### ISSUE TITLE
remote use on LAN?

### ISSUE THREAD

**Issue by caniyabanci76** [jiayev/GPT4V-Image-Captioner#17]
Hi, can gradio be started with `--listen` so that it can be used on another computer on the same network?

**Comment by SleeeepyZhou** [comment]
Thank you for the proposal! I have updated this, and now can access the LAN interface by using the address and port number. 
![image](https://github.com/jiayev/GPT4V-Image-Captioner/assets/80639626/e9fb6023-e6ea-4ab9-b6d6-3786512d7174)
For example, in the picture
I can use it on the LAN through 192.168.31.247:8848
