### ISSUE TITLE
Error: "install_cn.ps1 cannot be loaded because running scripts is disabled on this system"

### ISSUE THREAD

**Issue by Vigilence** [jiayev/GPT4V-Image-Captioner#18]
I redownloaded and now have this issue when trying to install via the install_windows.bat file.  I didn't have this issue previously.

```
Python installed.
Use CN
File I:\GPT4V-Image-Captioner\install_script\![Screenshot 2024-01-19 012838](https://github.com/jiayev/GPT4V-Image-Captioner/assets/22781570/3eaab6f8-114a-4349-8361-aded2a85d7d3). For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
Press any key to continue . . .
```

![Screenshot 2024-01-19 012838](https://github.com/jiayev/GPT4V-Image-Captioner/assets/22781570/4811c03e-d9b8-4097-a881-9067f155fcee)

**Comment by stinbuaa** [comment]
你用管理员权限打开powershell，输入Set-ExecutionPolicy Unrestricted按回车，然后重新安装下看看会不会报错哈

**Comment by SleeeepyZhou** [comment]
Powershell has now been deprecated and replaced with bat scripts. You can update and try again.
