### ISSUE TITLE
add Llama3 and Claude 

### ISSUE THREAD

**Issue by rafstahelin** [jiayev/GPT4V-Image-Captioner#46]
Would be amazing to add add Llama3 and Claude local models when available. Chatgpt api works great for me but a little pricy. Runs 0.07 dollars a caption. Ideally it would be 1/10th of that. Or local

**Comment by davizca** [comment]
Yeah, I think it could be an awesome addition, specially Claude which nowadays is pretty popular.

**Comment by jiayev** [comment]
Currently I don't have Anthropic API to test it out. As for Llama 3 and other local models, you may wanna try out tools like llama.cpp which provides OpenAI API compatible APIs.

**Comment by rafstahelin** [comment]
It's really too bad cuz Claude is just as good as Gpt, at a fraction of the price. How easy it would be to add a few lines of code to accept switching to Claude in the API config and login

**Comment by jiayev** [comment]
Hi, I just added support for Claude 3 apis, not sure if i'd work though. Would you mind trying it out and give feedback?

**Comment by rafstahelin** [comment]
@jiayev just tied it

returns:
`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
HTTP Error: 404 Client Error: Not Found for url: https://api.anthropic.com/`

Could not see an option for claude in config after git pull
![image](https://github.com/jiayev/GPT4V-Image-Captioner/assets/64715158/e3312515-5026-454d-a833-7d358f5e6a77)

![image](https://github.com/jiayev/GPT4V-Image-Captioner/assets/64715158/e1d74d08-9294-4b00-9443-afae99b3d6c6)

**Comment by jiayev** [comment]
You may try add '/v1/messages' after url

**Comment by rafstahelin** [comment]
still getting it

![image](https://github.com/jiayev/GPT4V-Image-Captioner/assets/64715158/d13992e6-fb0f-4112-89ec-f4be0728a99e)

**Comment by jiayev** [comment]
Hmm. I'll see what I can do.

**Comment by jiayev** [comment]
> 'x-api-key:' is wrong, 'x-api-key' is right, after delete the colon from the code,it's work

can't believe how ignorant i was
