### ISSUE TITLE
标签管理页面 Top N 标签传参是浮点型

### ISSUE THREAD

**Issue by vinsonliux** [jiayev/GPT4V-Image-Captioner#7]
标签管理页面 Top N 标签传参是浮点型，在代码中会报不是integer。

**Comment by facok** [comment]
我这里测试没能复现这个问题，功能使用正常，可以的话请提供更多线索，比如操作过程、gradio版本或者其它信息

**Comment by SleeeepyZhou** [comment]
前段时间应该大概是顺手修复了，如果更新后没有再次出现的话应该可以关掉了。
