### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by canyca** [jiayev/GPT4V-Image-Captioner#8]
请按任意键继续. . . Traceback (most recent call last):
  File "E:\GPT4V-Image-Captioner-main\gpt-caption.py", line 27, in <module>
    import Translator
  File "E:\GPT4V-Image-Captioner-main\Translator.py", line 55
    {"role": "user", "content": f"����һ��Ӣ����ר�ң���ֱ�ӷ���'{text}'���п��ܵ��������ķ�����������Զ��ż��."}
                                                                                                      ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

**Comment by SleeeepyZhou** [comment]
This is a previous encoding error that has been fixed. Please update and try again.
